### ISSUE TITLE
Inverted parameters for Flanger effect

### ISSUE THREAD

**Issue by JonasFolletete** [Stinkdigital/sono#3]
In the flanger effects, parameters attribution for frequency and gain seems inverted : 

```javascript
  lfo.frequency.value = validify(config.gain, 0.002); // 0.05 > 5
  gain.gain.value = validify(config.frequency, 0.25); // 0.0005 > 0.005
```

https://github.com/Stinkdigital/sono/blob/master/src/lib/effect/flanger.js#L17-L18 (line 17&18)

**Comment by ianmcgregor** [comment]
Fixed in latest build
